/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gym.view;

import com.gym.Class.model.ClassDAO;
import com.gym.Class.model.ClassDTO;
import com.gym.Member.model.MemberDAO;
import com.gym.Member.model.MemberDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author STU-13
 */
public class AdminFrame extends javax.swing.JFrame implements ActionListener,MouseListener{
    private ClassDAO cdao;
    private MemberDAO mdao;
    private String[] colNames3 = {"번호","강좌명","강사","시간","인원수","남은자리"};
    private String[] colNames4 = {"회원번호","이름","전화번호","이메일","등록일","프로그램"};
    private DefaultTableModel model3;
    private DefaultTableModel model4;
    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        
        init();
        addEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        tfClassName = new javax.swing.JTextField();
        tfTeacher = new javax.swing.JTextField();
        tfClassTime = new javax.swing.JTextField();
        tfLimit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btDel = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfclassno = new javax.swing.JTextField();
        btLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 600));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "회원번호", "이름", "전화번호", "이메일", "등록일", "프로그램"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("홈", jPanel1);

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "번호", "강좌명", "강사", "시간", "인원수", "남은자리"
            }
        ));
        jScrollPane2.setViewportView(table3);

        btAdd.setText("추가");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        jLabel5.setText("강좌명");

        jLabel6.setText("강사");

        jLabel7.setText("시간");

        jLabel8.setText("인원수");

        btDel.setText("삭제");

        btEdit.setText("수정");

        jLabel1.setText("번호");

        tfclassno.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(tfClassTime, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(tfTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(tfClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(tfclassno))
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfclassno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClassTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("클래스 관리", jPanel2);

        btLogout.setText("로그아웃");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table3;
    public javax.swing.JTable table4;
    private javax.swing.JTextField tfClassName;
    private javax.swing.JTextField tfClassTime;
    private javax.swing.JTextField tfLimit;
    private javax.swing.JTextField tfTeacher;
    private javax.swing.JTextField tfclassno;
    // End of variables declaration//GEN-END:variables
    private void init() {
        cdao = new ClassDAO();
        mdao = new MemberDAO();
        model3 = new DefaultTableModel();
        model4 = new DefaultTableModel();
        try {
            showTable3();
            showTable4();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addEvent() {
        table3.addMouseListener(this);
        btAdd.addActionListener(this);
        btDel.addActionListener(this);
        btEdit.addActionListener(this);
        table4.addMouseListener(this);
        btLogout.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btAdd){
            try {
                InsertClass();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else if(e.getSource()==btEdit){
            try {
                EditClass();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else if(e.getSource()==btDel){
            try {
                DelClass();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else if(e.getSource()==btLogout){
            this.dispose();
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
        }
    }

     @Override
    public void mouseClicked(MouseEvent e) {
        if(e.getSource()==table3){
            int row = table3.getSelectedRow();
            String classno = (String)table3.getValueAt(row, 0);
            String classname = (String)table3.getValueAt(row, 1);
            String teacher = (String)table3.getValueAt(row, 2);
            String time = (String)table3.getValueAt(row, 3);
            String limit = (String)table3.getValueAt(row, 4);

            tfclassno.setText(classno);
            tfClassName.setText(classname);
            tfTeacher.setText(teacher);
            tfClassTime.setText(time);
            tfLimit.setText(limit);
        }else if(e.getSource()==table4){
            try {
                int row = table4.getSelectedRow();
                String email = (String)table4.getValueAt(row, 3);
                MemberDTO dto = mdao.selectMember(email);
                AdminMemberFrame f = new AdminMemberFrame(this,dto);
                f.setVisible(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    private void InsertClass() throws SQLException {
        //1
        String classname = tfClassName.getText();
        String teacher = tfTeacher.getText();
        String time = tfClassTime.getText();
        int limit = Integer.parseInt(tfLimit.getText());
        
        //2
        ClassDTO dto = new ClassDTO();
        dto.setClassName(classname);
        dto.setTeacher(teacher);
        dto.setTime(time);
        dto.setLimit(limit);
        
        int cnt = cdao.insert(dto);
        System.out.println("클래스 입력 결과 cnt="+cnt);
        
        //3.
        showTable3();
    }

    private void EditClass() throws SQLException {
        //1
        int classno = Integer.parseInt(tfclassno.getText());
        String classname = tfClassName.getText();
        String teacher = tfTeacher.getText();
        String time = tfClassTime.getText();
        int limit = Integer.parseInt(tfLimit.getText());
        
        //2
        ClassDTO dto = new ClassDTO();
        dto.setClassNo(classno);
        dto.setClassName(classname);
        dto.setTeacher(teacher);
        dto.setTime(time);
        dto.setLimit(limit);
        
        int cnt = cdao.update(dto);
        System.out.println("클래스 수정 결과 cnt="+cnt);
        
        //3.
        showTable3();
    }

    private void DelClass() throws SQLException {
        //1
        int classno = Integer.parseInt(tfclassno.getText());
        //2
        int cnt = cdao.delete(classno);
        System.out.println("클래스 삭제 결과 cnt="+cnt);
        
        //3.
        showTable3();
    }

    public void showTable3() throws SQLException{
        //1.
        //2.
        ArrayList<ClassDTO> list = cdao.selectAll();
        
        if(list==null || list.isEmpty()){
            JOptionPane.showMessageDialog(this, "데이터가 없습니다.");
            return;
        }
        //3.
        String[][] data = new String[list.size()][colNames3.length];
        
        for(int i=0; i<list.size(); i++){
            ClassDTO dto = list.get(i);
            
            data[i][0]=dto.getClassNo()+"";
            data[i][1]=dto.getClassName();
            data[i][2]=dto.getTeacher();
            data[i][3]=dto.getTime();
            data[i][4]=dto.getLimit()+"";
            data[i][5]=dto.getLeft()+"";
        }
        model3.setDataVector(data, colNames3);
        table3.setModel(model3);
    }

    public void showTable4() throws SQLException {
        //1.
        //2.
        ArrayList<MemberDTO> list = mdao.selectAll();
        if(list==null || list.isEmpty()){
            JOptionPane.showMessageDialog(this, "데이터가 없습니다.");
            return;
        }
        //3.
        String[][] data = new String[list.size()][colNames4.length];
        
        for(int i=0; i<list.size(); i++){
            MemberDTO dto = list.get(i);
            System.out.println("dto= "+dto);
           
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            data[i][0]=dto.getMemNo()+"";
            data[i][1]=dto.getMemName();
            data[i][2]=dto.getMemTel();
            data[i][3]=dto.getMemEmail();
            data[i][4]= sdf.format(dto.getMemRegdate());
           
            int progno = dto.getProgNo();
            String program="";
            switch(progno){
                case 100: program="기본사용권";break;
                case 101: program="다이어트PT";break;
                case 102: program="재활PT";break;
                case 103: program="웨딩케어PT";break;
                case 104: program="체형교정PT";break;
                case 105: program="산후PT";break;
                case 106: program="운동선수PT";break;
                case 107: program="토탈PT";break;
            }
            data[i][5]=program;
        }
        model4.setDataVector(data, colNames4);
        table4.setModel(model4);
    }

    @Override
    public void mousePressed(MouseEvent e) {}
    @Override
    public void mouseReleased(MouseEvent e) {}
    @Override
    public void mouseEntered(MouseEvent e) {}
    @Override
    public void mouseExited(MouseEvent e) {}
    
}
