/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package com.gym.view;

import com.gym.Attend.model.AttendDAO;
import com.gym.Member.model.MemberDAO;
import com.gym.Member.model.MemberDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author STU-13
 */
public class MemberFrame extends javax.swing.JFrame implements ActionListener{
    private MemberDAO dao = new MemberDAO();
    private AttendDAO Adao = new AttendDAO();
    private LoginFrame Lf;
    private boolean isDuplicate;
    private String email;
    /**
     * Creates new form MemberFrame
     */
    public boolean getisDuplicate(){
        return isDuplicate;
    }
    public void setisDuplicate(boolean isDuplicate){
        this.isDuplicate = isDuplicate;
    }
    public MemberFrame() {
        initComponents();
        
        init();
        addEvent();
    }
    public MemberFrame(LoginFrame Lf) {
        this();
        
        this.Lf=Lf;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        tfEmail1 = new javax.swing.JTextField();
        tfPwd = new javax.swing.JPasswordField();
        cbTel1 = new javax.swing.JComboBox<>();
        tfTel2 = new javax.swing.JTextField();
        tfTel3 = new javax.swing.JTextField();
        tfZipcode = new javax.swing.JTextField();
        tfAddress1 = new javax.swing.JTextField();
        tfAddress2 = new javax.swing.JTextField();
        btDup = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        cbProg = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("이름");

        jLabel2.setText("이메일");

        jLabel3.setText("비밀번호");

        jLabel4.setText("전화번호");

        jLabel5.setText("우편번호");

        jLabel6.setText("주소");

        jLabel7.setText("상세주소");

        btRegister.setText("회원가입");

        cbTel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "010", "011", "012", "013", "014", "015", "016", "017", "050", "060", "070", " " }));

        btDup.setText("중복확인");

        btSearch.setText("번호검색");

        cbProg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "기본사용권", "다이어트PT", "재활PT", "웨딩케어PT", "체형교정PT", "산후PT", "운동선수PT", "토탈PT" }));

        jLabel9.setText("가입상품");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16)
                            .addComponent(tfTel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfAddress2)
                        .addComponent(tfAddress1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tfZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfPwd)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbProg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDup)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDup))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(39, 39, 39)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDup;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btSearch;
    private javax.swing.JComboBox<String> cbProg;
    private javax.swing.JComboBox<String> cbTel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    public javax.swing.JTextField tfAddress1;
    private javax.swing.JTextField tfAddress2;
    public javax.swing.JTextField tfEmail1;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPwd;
    private javax.swing.JTextField tfTel2;
    private javax.swing.JTextField tfTel3;
    public javax.swing.JTextField tfZipcode;
    // End of variables declaration//GEN-END:variables
    
    private void init() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private void addEvent() {
        btRegister.addActionListener(this);
        btDup.addActionListener(this);
        btSearch.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btRegister){
            try {
                register();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else if(e.getSource()==btDup){
            SubEmail f = new SubEmail(this,tfEmail1.getText());
            f.setVisible(true);
        }else if(e.getSource()==btSearch){
            Subzipcode f = new Subzipcode(this);
            f.setVisible(true);
        }
    }
    
    private void register() throws SQLException {
            //1
            String memname = tfName.getText();
            String mememail = tfEmail1.getText();
            String mempwd = tfPwd.getText();
            String tel2=tfTel2.getText();
            String tel3=tfTel3.getText();
            String memtel="";
            String memzip = tfZipcode.getText();
            String memaddr = tfAddress1.getText();
            String memaddrdetail = tfAddress2.getText();
            
            int progno  = 100;
            
            int program = cbProg.getSelectedIndex();
            
            switch(program){
                case 0:
                    break;
                case 1:
                    progno=101;
                    break;
                case 2:
                    progno=102;
                    break;
                case 3:
                    progno=103;
                    break;
                case 4:
                    progno=104;
                    break;
                case 5:
                    progno=105;
                    break;
                case 6:
                    progno=106;
                    break;
                case 7:
                    progno=107;
                    break;
            }
            
            if(memname==null || memname.isEmpty()){
                JOptionPane.showMessageDialog(this, "이름을 입력하세요");
                tfName.requestFocus();
                return;
            }if(mempwd==null || mempwd.isEmpty()){
                JOptionPane.showMessageDialog(this, "비밀번호를 입력하세요");
                tfPwd.requestFocus();
                return;
            }if(mememail==null || mememail.isEmpty()){
                JOptionPane.showMessageDialog(this, "이메일을 입력하세요");
                tfEmail1.requestFocus();
                return;
            }if(!isDuplicate){
                JOptionPane.showMessageDialog(this, "중복확인을 해주세요");
                btDup.requestFocus();
                return;
            }if(tel2!=null && !tel2.isEmpty() && tel3!=null && !tel3.isEmpty()){
                memtel = cbTel1.getSelectedItem().toString()+"-"+tel2+"-"+tel3;
            }else{
                JOptionPane.showMessageDialog(this, "전화번호를 바르게 입력해주세요");
                return;
            }
            
            
            //2
            MemberDTO dto = new MemberDTO();
            dto.setMemAddr(memaddr);
            dto.setMemAddrDetail(memaddrdetail);
            dto.setMemEmail(mememail);
            dto.setMemName(memname);
            dto.setMemPwd(mempwd);
            dto.setMemTel(memtel);
            dto.setMemZip(memzip);
            dto.setProgNo(progno);
            
            int cnt = dao.insertMember(dto);
            
            //3
            if(cnt>0){
                Lf.tfEmail.setText(mememail);
                MemberDTO mdto = dao.selectMember(email);//해당 회원 정보 가져오기
                Adao.printAtt(mdto.getMemNo());//출석 저장 실행
                JOptionPane.showMessageDialog(this, "회원가입 되었습니다!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "회원가입 실패!");
                return;
            }
            
    }
    
    private void showMember() throws SQLException {
        //1
        //2
        MemberDTO dto = dao.selectMember(email);
        
        //3
        tfAddress1.setText(dto.getMemAddr());
        tfAddress2.setText(dto.getMemAddrDetail());
        tfName.setText(dto.getMemName());
        tfZipcode.setText(dto.getMemZip());
        int progno = dto.getProgNo()-100;
        cbProg.setSelectedIndex(progno);
        String hp = dto.getMemTel();
        
        if(hp!=null && !hp.isEmpty()){
            String[] hpArr=hp.split("-");
            tfTel2.setText(hpArr[1]);
            tfTel3.setText(hpArr[2]);
            cbTel1.setSelectedItem(hpArr[0]);
        }
    }
    
}
